# on each push to main, increment version & refresh docs

name: Post-push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Configure git
      run: |
        git config --global user.name "version bot"
        git config --global user.email "<>"
    - name: Increment version
      run: |
        OLD_VERSION=$(grep version setup.py | grep -Po "\d+.\d+.\d+")
        NEW_VERSION=$(echo $OLD_VERSION | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e')
        for file in setup.py docsrc/conf.py; do
            sed s/$OLD_VERSION/$NEW_VERSION/g $file -i
            git add $file
        done
        git commit -m "Release $NEW_VERSION [no ci]"
        git tag $NEW_VERSION
        git push origin main:main
        git push origin $NEW_VERSION
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Update documentation
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
        docsrc/build
    - name: Configure git
      run: |
        git config --global user.name "version bot"
        git config --global user.email "<>"
    - name: Publish to GitHub pages
      run: |
        git add docs -f
        git commit docs -m "Updating Documentation"
        git push origin main:docs -f
